import { Jersey, EncargoJersey } from './types';

export const WHATSAPP_NUMBER = '+5355859998';

export const JERSEYS: Jersey[] = [
  // Temporada 25/26
  {
    id: 'rma-home-25-valverde',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1PL8e-1T_GJzW8_fJYkHOVYTktoceqibj',
    style: 'Fan',
    size: 'XL',
    season: '25/26',
    type: 'Local',
    playerName: 'VALVERDE',
    number: '8',
    patch: 'Champions'
  },
  {
    id: 'bar-away-25-kounde',
    name: 'Barcelona - Visitante - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1ycaNuDvea08ARCMCCM0E6U7i4nSII_PY',
    style: 'Fan',
    size: 'XXL',
    season: '25/26',
    type: 'Visitante',
    playerName: 'KOUNDE',
    number: '23',
    patch: 'La Liga'
  },
  {
    id: 'rma-home-25-mbappe',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1u2qHmjqHrqBRMo7r1iGf0lYZcqi2u0TO',
    style: 'Fan',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'MBAPPÉ',
    number: '10',
    patch: 'Champions'
  },
  {
    id: 'bar-home-25-dejong',
    name: 'Barcelona - Local - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1TlV_9qzEPctLo82j69nSobBgHAFZyE2s',
    style: 'Player',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'DE JONG',
    number: '21',
    patch: 'Champions'
  },
  {
    id: 'mia-third-25-messi',
    name: 'Inter de Miami - Tercera - 25/26',
    team: 'Inter de Miami',
    league: 'MLS',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1i_Oxtk6ZPtMMAuOdwt9W-cJ7NFJDz2WC',
    style: 'Player',
    size: 'XL',
    season: '25/26',
    type: 'Tercera',
    playerName: 'MESSI',
    number: '10',
    patch: 'MLS'
  },
  {
    id: 'psg-home-25-dembele',
    name: 'PSG - Local - 25/26',
    team: 'PSG',
    league: 'Ligue 1',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/11MOE3-eNKU3kbnatuY16gJNjXeyplHyB',
    style: 'Player',
    size: 'L',
    season: '25/26',
    type: 'Local',
    playerName: 'DEMBÉLÉ',
    number: '10',
    patch: 'Champions'
  },
  {
    id: 'rma-home-25-bellingham',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1vQR7WbtxXvDz7s9EmlJefSZKDIIDoscD',
    style: 'Player',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'BELLINGHAM',
    number: '5',
    patch: 'Champions'
  },
  {
    id: 'bar-home-25-lamine',
    name: 'Barcelona - Local - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1zgfqFdSpqC7krzHGglYdJ3_Se96VfX3r',
    style: 'Player',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'LAMINE YAMAL',
    number: '10',
    patch: 'Champions'
  },
  // Temporada 24/25
  {
    id: 'bar-home-24-lewandowski',
    name: 'Barcelona - Local - 24/25',
    team: 'Barcelona',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1bp_uMdhYwyU4W1jhM3QPTBp_0RdVJOZ_',
    style: 'Fan',
    size: 'M',
    season: '24/25',
    type: 'Local',
    playerName: 'LEWANDOWSKI',
    number: '9',
    patch: 'Champions'
  },
  {
    id: 'mci-home-24-haaland',
    name: 'Manchester City - Local - 24/25',
    team: 'Manchester City',
    league: 'Premier League',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1LeVhXFpq4zDKFozdUJAcRgaKbGu5hol0',
    style: 'Fan',
    size: 'XL',
    season: '24/25',
    type: 'Local',
    playerName: 'HAALAND',
    number: '9',
    patch: 'Champions'
  },
  // Año 2024
  {
    id: 'esp-home-24-lamine',
    name: 'España - Local - 2024',
    team: 'España',
    league: 'Selecciones',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1z_yJwr8pC_82SFNuOmMar2yeELS59xw9',
    style: 'Fan',
    size: 'XXL',
    season: '2024',
    type: 'Local',
    playerName: 'LAMINE YAMAL',
    number: '19',
    patch: 'Eurocopa'
  },
  // Temporada 22/23
  {
    id: 'psg-home-22-messi',
    name: 'PSG - Local - 22/23',
    team: 'PSG',
    league: 'Ligue 1',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1J1MuEWNhT_E2sHJQlLTasCDKZizGq9FZ',
    style: 'Fan',
    size: 'M',
    season: '22/23',
    type: 'Local',
    playerName: 'MESSI',
    number: '30',
    patch: 'Ligue 1'
  },
  // Temporada 14/15
  {
    id: 'rma-retro-14-ronaldo',
    name: 'Real Madrid - Local - 14/15',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1d5VR1wCAhgtQcI6VQ-_6O1YqW-voXcod',
    style: 'Retro',
    size: 'XXL',
    season: '14/15',
    type: 'Local',
    playerName: 'RONALDO',
    number: '7',
    patch: 'Champions'
  },
  {
    id: 'bar-retro-14-suarez',
    name: 'Barcelona - Local - 14/15',
    team: 'Barcelona',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1qavn8778lnjxVqrFtB2ZumQ_N1LLwR4p',
    style: 'Retro',
    size: 'L',
    season: '14/15',
    type: 'Local',
    playerName: 'SUÁREZ',
    number: '9',
    patch: 'Champions'
  },
  // Temporada 13/14
  {
    id: 'rma-retro-13-ramos',
    name: 'Real Madrid - Local - 13/14',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1J8x7pXaTqy1ucwanqlbEBe9rEpUUoRbO',
    style: 'Retro',
    size: 'L',
    season: '13/14',
    type: 'Local',
    playerName: 'SERGIO RAMOS',
    number: '4',
    patch: 'Champions'
  },
  // Temporada 05/06
  {
    id: 'ars-retro-05-henry',
    name: 'Arsenal - Local - 05/06',
    team: 'Arsenal',
    league: 'Premier League',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1-Kjzch1Fjv7IS9LvPclKuzjpoSby41nK',
    style: 'Retro',
    size: 'M',
    season: '05/06',
    type: 'Local',
    playerName: 'HENRY',
    number: '14',
    patch: 'Premier League'
  },
  // Temporada 1990
  {
    id: 'ger-retro-90-matthaus',
    name: 'Alemania - Local - 1990',
    team: 'Alemania',
    league: 'Selecciones',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1fZ5zARjTmJOg96y7vKKR4IaC8BUNidqQ',
    style: 'Retro',
    size: 'L',
    season: '1990',
    type: 'Local',
    playerName: 'MATTHÄUS',
    number: '10',
    patch: 'Sin Parche'
  }
];

export const LEAGUES = ['Premier League', 'La Liga', 'Serie A', 'Bundesliga', 'Selecciones'];

export const ENCARGO_JERSEYS: EncargoJersey[] = [
  // BARCELONA
  {
    id: 'fcb-home-26-custom',
    name: 'Barcelona - Local - 26/27 (Filtración)',
    team: 'Barcelona',
    league: 'La Liga',
    season: '26/27',
    type: 'Local',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1aKTFWdSR3FthIdAHsL299SO_mPeNHAg8&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1Z_k2m1fA-SPTNIFHo9eJKS9CvOOFrrwh&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1C1VNTWVz0rKx-mKXlDl-iXGXRkfR6cVY&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1VPcgeHFRmnTNSjkBzS6K05ihBilIFzu5&sz=w800'
  },
  {
    id: 'fcb-home-25-custom',
    name: 'Barcelona - Local - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Local',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1IaVDX8IyF8d6kAY1Tgbd5ZPmscCfaRiK&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1WXj5Db-O3QS8NFGF0f0ziVlXTf3Uzxgq&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1JhsaUt3V-kcarp--JM6MZrX_A4C7dzLO&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1rPh5PQUvInKbDmx637FaeA3xUSBebSJy&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=17VokuqIUo0IiWrrGGFEUrQZhaoUXH-vh&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1C1VNTWVz0rKx-mKXlDl-iXGXRkfR6cVY&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1VPcgeHFRmnTNSjkBzS6K05ihBilIFzu5&sz=w800'
  },
  {
    id: 'fcb-away-25-custom',
    name: 'Barcelona - Visitante - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Visitante',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=141U1mXUKPJgOBJKq4shipF3PPz8JlWnJ&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1yxRcEDVqfCGa0jjLUPWbBqMzO7DM2qjd&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1glKizFCwZ1K4OqZWWs-oXw2am8hFrTDh&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1G6i3w5x9HHr4tbHHsJbAJQ0WxQamjXev&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1TFzZImQB803BH1fu4V_j-IDToRtn3ly-&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1C1VNTWVz0rKx-mKXlDl-iXGXRkfR6cVY&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1VPcgeHFRmnTNSjkBzS6K05ihBilIFzu5&sz=w800'
  },
  {
    id: 'fcb-third-25-custom',
    name: 'Barcelona - Tercera - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Tercera',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1MuxdML7QKTrEbcwbi02EEabG8saA77PJ&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=16F49lrFwUDHY6WA_2AoO0O3lhUEGSE8n&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1qX_6rekrALxATHDwqDWnXLEj0NpPBNQ2&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1eAvH9AThCM9nX6zyS9ViDKNZjhgLZvKV&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1js-EPG9kk6mcq5bTuAz_tzhCFQDchp-B&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1y0OFkIikgpJW72cwdDI_NAKHj92oKJH4&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1AgqC1SkOA6lpy2sGD9BbOeDp-DnWasd3&sz=w800'
  },
  {
    id: 'fcb-fourth-25-custom',
    name: 'Barcelona - Cuarta - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Cuarta',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1XMPz1YwN6hhuNA6FrkI0MHiy1CwMGpIW&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1G-aw_I9T3k0Z0HRA06RNMattG8UYZ1ph&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1GjRmwtrZ4ZYHHfimL_z9o58MqYRyK6Ir&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1C1VNTWVz0rKx-mKXlDl-iXGXRkfR6cVY&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1VPcgeHFRmnTNSjkBzS6K05ihBilIFzu5&sz=w800'
  },
  {
    id: 'fcb-home-24-custom',
    name: 'Barcelona - Local - 24/25',
    team: 'Barcelona',
    league: 'La Liga',
    season: '24/25',
    type: 'Local',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1l-x_PYRnULNKQ2DIyVyyrWYjgu3qlBD7&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1zas77PxtqBz2CRj--07o5HB0EQvs_2K6&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1fZKbEO3X9xuOviYHhlAlfsyTD4IhlJz0&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1C1VNTWVz0rKx-mKXlDl-iXGXRkfR6cVY&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1VPcgeHFRmnTNSjkBzS6K05ihBilIFzu5&sz=w800'
  },
  {
    id: 'fcb-away-24-custom',
    name: 'Barcelona - Visitante - 24/25',
    team: 'Barcelona',
    league: 'La Liga',
    season: '24/25',
    type: 'Visitante',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1HB2Yypn7cxAUmtPSF7r3g5gi7I7I5hs9&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1fbJFqMZJnXTODyGCwdpfu58Iq9dX_Nko&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1tOArg7x_v2kJM3U8vZ1pQqruDIUpPJmU&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1C1VNTWVz0rKx-mKXlDl-iXGXRkfR6cVY&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1VPcgeHFRmnTNSjkBzS6K05ihBilIFzu5&sz=w800'
  },
  {
    id: 'fcb-special-travis-24-custom',
    name: 'Barcelona - Especial Travis Scott - 24/25',
    team: 'Barcelona',
    league: 'La Liga',
    season: '24/25',
    type: 'Especial',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1hB1yIZ3g3s5Y-DmupfxW44dhTh-rqiw7&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1cL1scn_8gL7DC7FzSRhSw7bEipf9eJ0M&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=15X62FjZb8i33-fRb--uDZ_UKS84AJFAd&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=15X62FjZb8i33-fRb--uDZ_UKS84AJFAd&sz=w800'
  },
  {
    id: 'fcb-special-125-24-custom',
    name: 'Barcelona - Especial 125 Aniversario - 24/25',
    team: 'Barcelona',
    league: 'La Liga',
    season: '24/25',
    type: 'Especial',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1u56CBOuwcgAny8Lc2VrmPjEAR7cHVgfy&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1fHAiv09JbOa1j_Tt5l5-bqFuLTJmd9H7&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1_3E2cy3SqQJHLnH4-4PXNEbL4E8SKWPz&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1C1VNTWVz0rKx-mKXlDl-iXGXRkfR6cVY&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1VPcgeHFRmnTNSjkBzS6K05ihBilIFzu5&sz=w800'
  },
  {
    id: 'fcb-retro-14-custom',
    name: 'Barcelona - Local - 14/15',
    team: 'Barcelona',
    league: 'La Liga',
    season: '14/15',
    type: 'Local',
    price: 35,
    isRetro: true,
    fanImage: 'https://lh3.googleusercontent.com/d/1GTniTG39_yjViqYl7z216Gh_4-l1EboL',
    childImage: 'https://lh3.googleusercontent.com/d/1Q6ScKKoBnKqj8EsOKrdqXiy_kUQWxxI',
    retroLongSleeveImage: 'https://lh3.googleusercontent.com/d/1oFdGnM22E_SoJtPG5QTwdhjwFaI8V0iS',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1utfJfyAxf5Si43bdhsmWzSvxS1lQL9xC&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1utfJfyAxf5Si43bdhsmWzSvxS1lQL9xC&sz=w400'
  },
  {
    id: 'fcb-retro-99-custom',
    name: 'Barcelona - Local - 99/00',
    team: 'Barcelona',
    league: 'La Liga',
    season: '99/00',
    type: 'Local',
    price: 35,
    isRetro: true,
    fanImage: 'https://lh3.googleusercontent.com/d/1LMj5kdVhIW-WNxEuV8YIna3ntvo7yx4w',
    childImage: 'https://lh3.googleusercontent.com/d/1Jv_hPYzs-bL9v_EPwE0mBRGN_WrB1go8',
    retroLongSleeveImage: 'https://lh3.googleusercontent.com/d/1qSajSC7QgC-vX_H86ZpCVk3_yN5a4cLE',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1qZi8DU8OYcmBwha0rftTK8wycogf85Cw&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1qZi8DU8OYcmBwha0rftTK8wycogf85Cw&sz=w400'
  },
  // REAL MADRID
  {
    id: 'rma-home-26-custom',
    name: 'Real Madrid - Local - 26/27 (Filtración)',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '26/27',
    type: 'Local',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1VK21ZFoDp4A3n6g5eJosel1qJKeepeRV&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=14OicIliCEKJ9IpZn4Wk5NgeJH3ZfRMm0&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=15dbEMtc7bPoWEE-T_1YKtEUiFbjdIDWq&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=19Y-BdA2MOpr_5x29IN5ic9n-mtMej5p7&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=19Y-BdA2MOpr_5x29IN5ic9n-mtMej5p7&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800'
  },
  {
    id: 'rma-home-25-custom',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Local',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1AH4RKI-MqNVtNjK6rguPg9EeU7LlF2Jq&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1wuGIplPIpXi_1L99PHk05vArGlwZoU2k&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1qE7izWdNW-6DNz9AfVICSomOcwDIIX_F&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1U0ovSfNbZhPowfYv31YM5zonz04zpIx0&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1SxU05Jk6giWUpmpHgOO28AlqPHoc7MkD&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800'
  },
  {
    id: 'rma-away-25-custom',
    name: 'Real Madrid - Visitante - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Visitante',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1CxGWC4Ukwc9mgwqkJVN5apkq0m6mzxZo&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1WmNeCcv4sffZ0aRrQB0Ll7cfHmYC9UEU&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=11JOGBLn88iHoU7TpZhSkTUz0R92abv9k&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1Bo6HC4YyGAI9Q9vaMKTSyQBVmfZs_UDm&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=12w4w495cNSQpZ6U-FsiTvSVL--2naqc7&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800'
  },
  {
    id: 'rma-third-25-custom',
    name: 'Real Madrid - Tercera - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Tercera',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1dboBptHF67paAVK-kAI5mjYOJydu-k_O&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1kt-l4Meh-0ng-DHLu4mdsQBL87kHosZJ&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1wKMLlecsOHJRWBsyb6FvfP5ZSFfx-UMW&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1x1rLvp-Ormcd_IfaXFPsXnYFe8sijiFm&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1zXoAVw3A6htE54m8NKDEhrNVVA8MkXfr&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800'
  },
  {
    id: 'rma-gk-third-25-custom',
    name: 'Real Madrid - Portero (Tercera) - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Portero',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1HsxTDxSdG4L-ljZUg6k-EP_UInBfCpzs&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1PnaZt1IMIgR1-NAJizw5v1PhRXDvTyvd&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1XlVQab9IxXPhaqxnhOVRk6buK-EDOWRn&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=10nJyjR2MLIyVWthrvmYv8-gQQZVgpxzr&sz=w800'
  },
  {
    id: 'rma-third-24-custom',
    name: 'Real Madrid - Tercera - 24/25',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '24/25',
    type: 'Tercera',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1jkQqss_cOIxU8DsLGA26st7V4oNQFfNk&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1LxCNyn6fgOnH4PKdvGPEI__sDv6rVnPJ&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1mDuC9KSCJb5dgrKpiQ_KtDevukxnigzD&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1Sl7uBqOoKRx8SuNNkDGeucj_kMmQqlKg&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1nP27mMN5uM5UQc0q8-Q8O3BCzcSzxyYz&sz=w800'
  },
  {
    id: 'rma-retro-19-custom',
    name: 'Real Madrid - Local - 19/20',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '19/20',
    type: 'Local',
    price: 35,
    isRetro: true,
    fanImage: 'https://drive.google.com/thumbnail?id=1AfEjDYxfMzW6L9ac2O5Ro38bBtgLCZox&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1dClGSPthutjX8eCOipjY5aH-Yq18Xjkn&sz=w800',
    retroLongSleeveImage: 'https://drive.google.com/thumbnail?id=1SBSh8kV2KdLnruB8Rop-9tZ2ADmchXTe&sz=w800',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1G2nR8Su1NDlckFICWKQUYtY9bYq0rkyc&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1G2nR8Su1NDlckFICWKQUYtY9bYq0rkyc&sz=w800'
  },
  {
    id: 'rma-retro-17-custom',
    name: 'Real Madrid - Local - 17/18',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '17/18',
    type: 'Local',
    price: 35,
    isRetro: true,
    fanImage: 'https://drive.google.com/thumbnail?id=15QjlsFlcS9_quIZmIbbqYDWrItzHKMhC&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=19dxUhTMGndPKbkyj_98TBISMlAGKJkRQ&sz=w800',
    retroLongSleeveImage: 'https://drive.google.com/thumbnail?id=1eaAnAnDC_IyZ9DPPlnQxLDqWmU3sGdNQ&sz=w800',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1CBplkqWX259k1qMk6peJBaNQ_YPzNeQH&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1CBplkqWX259k1qMk6peJBaNQ_YPzNeQH&sz=w800'
  },
  {
    id: 'rma-retro-14-away-custom',
    name: 'Real Madrid - Visitante - 14/15',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '14/15',
    type: 'Visitante',
    price: 35,
    isRetro: true,
    fanImage: 'https://drive.google.com/thumbnail?id=1j9jtGLLwckcJRKPjd3fffFPNxyo3dh8h&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1pxNwFntzXDPDXY5Znj8gwnYdWPaY3nDo&sz=w800',
    retroLongSleeveImage: 'https://drive.google.com/thumbnail?id=1IxkGxq4Jxv9qwODvrUUxwp2gKkdWY6JK&sz=w800',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1RKBJb6liSc4nr2PQBsg789UgBnHbqHXS&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1RKBJb6liSc4nr2PQBsg789UgBnHbqHXS&sz=w800'
  },
  {
    id: 'rma-retro-13-custom',
    name: 'Real Madrid - Local - 13/14',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '13/14',
    type: 'Local',
    price: 35,
    isRetro: true,
    fanImage: 'https://drive.google.com/thumbnail?id=1TwEYBRmrgnnYqlHPDNTg_DkF2ysPSpPQ&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1As78jpELZbIO4yjMlLXyYz6LdZvM3b7C&sz=w800',
    retroLongSleeveImage: 'https://drive.google.com/thumbnail?id=1Nzi9-nq9sWeZZemCjX-QCUsXxcO-f97Z&sz=w800',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1Tq9bhCEwyBuu_5syGIxIQNCwWE3gkPS2&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1Tq9bhCEwyBuu_5syGIxIQNCwWE3gkPS2&sz=w800'
  },
  {
    id: 'rma-retro-06-custom',
    name: 'Real Madrid - Local - 06/07',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '06/07',
    type: 'Local',
    price: 35,
    isRetro: true,
    fanImage: 'https://drive.google.com/thumbnail?id=187woklLvW6mr_XYW8AnT7F27kZ36VWT3&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1maZCGeX9GXQe_nRIgKI2ZzLtX7pZDQ5Y&sz=w800',
    retroLongSleeveImage: 'https://drive.google.com/thumbnail?id=1kvJlSUXzWub0Rg9ELo9l6So4Bk_R-Lng&sz=w800',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1I7de8Q1UA6YVoNUHmTEOTJGg2eQcnrDm&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1I7de8Q1UA6YVoNUHmTEOTJGg2eQcnrDm&sz=w800'
  },
  {
    id: 'rma-retro-00-custom',
    name: 'Real Madrid - Visitante - 00/01',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '00/01',
    type: 'Visitante',
    price: 35,
    isRetro: true,
    fanImage: 'https://drive.google.com/thumbnail?id=1t7d0MxSX8egK1ZPRHz11d1cJ45yHGqJc&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1i1kZacsZgYkGSo9tr98mQmLRQOmD_cb0&sz=w800',
    retroLongSleeveImage: 'https://drive.google.com/thumbnail?id=1gaZTJzTgGa-Lpsw7YY1w72gJiKonTYCO&sz=w800',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1TZ-NYwZ9GxxW2rLdzjralwKlktGOG_qR&sz=w800',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1TZ-NYwZ9GxxW2rLdzjralwKlktGOG_qR&sz=w800'
  },
  // ATLÉTICO DE MADRID
  {
    id: 'atm-home-25-custom',
    name: 'Atlético de Madrid - Local - 25/26',
    team: 'Atlético de Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Local',
    price: 30,
    fanImage: 'https://lh3.googleusercontent.com/d/1YQhmCk5bKRPoi-pPW5HggvAgX7weQuE7',
    playerImage: 'https://lh3.googleusercontent.com/d/1mkW3jb-CpYiSuiO3iacOD9g2v5veySDP',
    childImage: 'https://lh3.googleusercontent.com/d/1TMADGl64fwFpnaxKq8huHYoviRF2Sbmm',
    fanLongSleeveImage: 'https://lh3.googleusercontent.com/d/1Q78E1Dpx4PgATMhxTQcSMxccSW46ga0s',
    playerLongSleeveImage: 'https://lh3.googleusercontent.com/d/1di2qoKkkx2skcWeAgTRDoi_Gu_aFYUed',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1DRUQ3CDufI6pB9Mh1M8WPJ3IGUzbUEsH&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1eLiKsgEy7hxmefspa7-ldILI8d3DPkkM&sz=w400'
  },
  {
    id: 'atm-away-25-custom',
    name: 'Atlético de Madrid - Visitante - 25/26',
    team: 'Atlético de Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Visitante',
    price: 30,
    fanImage: 'https://lh3.googleusercontent.com/d/1gnwXy-wGXxx_e7OF744lEJJLRdhsQ06U',
    playerImage: 'https://lh3.googleusercontent.com/d/1dKjMtp4cDAd_gbhd4tmiubv3gL-iu7x_',
    childImage: 'https://lh3.googleusercontent.com/d/1hNRvJ6vlSQehL26fQpfVA09zH8v4mPyF',
    fanLongSleeveImage: 'https://lh3.googleusercontent.com/d/1tsz5CiwvCm52E3x4m7dFw_UnBmGFHilQ',
    playerLongSleeveImage: 'https://lh3.googleusercontent.com/d/1tsz5CiwvCm52E3x4m7dFw_UnBmGFHilQ',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1DRUQ3CDufI6pB9Mh1M8WPJ3IGUzbUEsH&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1eLiKsgEy7hxmefspa7-ldILI8d3DPkkM&sz=w400'
  },
  {
    id: 'atm-third-25-custom',
    name: 'Atlético de Madrid - Tercera - 25/26',
    team: 'Atlético de Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Tercera',
    price: 30,
    fanImage: 'https://lh3.googleusercontent.com/d/16bFb5ZFz5dBcf2nPSVWnfj24_GgO7j-C',
    playerImage: 'https://lh3.googleusercontent.com/d/1uthQPBS4MtTb7fnCmdR8IRXGOZ7V2jbe',
    childImage: 'https://lh3.googleusercontent.com/d/19Z6E5WHs2h1nES_V6zDISG73eq0x1YtR',
    fanLongSleeveImage: 'https://lh3.googleusercontent.com/d/1MXMYbjxW7LcppMtTKcRCpe4ZB6FaHdhZ',
    playerLongSleeveImage: 'https://lh3.googleusercontent.com/d/1MXMYbjxW7LcppMtTKcRCpe4ZB6FaHdhZ',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1DRUQ3CDufI6pB9Mh1M8WPJ3IGUzbUEsH&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1eLiKsgEy7hxmefspa7-ldILI8d3DPkkM&sz=w400'
  },
  {
    id: 'atm-home-24-custom',
    name: 'Atlético de Madrid - Local - 24/25',
    team: 'Atlético de Madrid',
    league: 'La Liga',
    season: '24/25',
    type: 'Local',
    price: 30,
    fanImage: 'https://lh3.googleusercontent.com/d/1Zjp1rs2IXQcrw_cYaDx1tNYEjh4GejEc',
    childImage: 'https://lh3.googleusercontent.com/d/15kCLIrmkp_Yez230tuHGaer3pZRzKEe1',
    fanLongSleeveImage: 'https://lh3.googleusercontent.com/d/113pbdDtQr5et3aKcS4DfAUmFrPbGYtLT',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1DRUQ3CDufI6pB9Mh1M8WPJ3IGUzbUEsH&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1eLiKsgEy7hxmefspa7-ldILI8d3DPkkM&sz=w400'
  },
  {
    id: 'atm-retro-04-custom',
    name: 'Atlético de Madrid - Local - 04/05',
    team: 'Atlético de Madrid',
    league: 'La Liga',
    season: '04/05',
    type: 'Local',
    price: 35,
    isRetro: true,
    fanImage: 'https://lh3.googleusercontent.com/d/1Qd3aAL5SxKu1rPVBWs7lh24KkS7nNlPx',
    childImage: 'https://lh3.googleusercontent.com/d/115ZJYGPUAoIgzuH53mqDksylBO6Z0y0v',
    retroLongSleeveImage: 'https://lh3.googleusercontent.com/d/1eXo5ls5me7XXBrJyGbRpPmLLMVaUsGK6',
    retroSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://lh3.googleusercontent.com/d/15lgPjqgPcCjs2SlpzckXPEc5bnKkJw1d',
    championsNumberingImage: 'https://lh3.googleusercontent.com/d/15lgPjqgPcCjs2SlpzckXPEc5bnKkJw1d'
  }
];

export const LEAGUES_DATA = [
  {
    name: 'La Liga',
    logo: 'https://drive.google.com/thumbnail?id=1ta7tkJUgwkYaXXxiRBAXTHU_iHSWHfOw&sz=w200',
    teams: [
      { name: 'Real Madrid', logo: 'https://drive.google.com/thumbnail?id=1UtV9rWSqUu5i8MUdGYHOFio4ssY01m9I&sz=w200' },
      { name: 'Barcelona', logo: 'https://drive.google.com/thumbnail?id=15-u5D0AvhJgrjQwUmcCHWZfUOgaAk_59&sz=w200' },
      { name: 'Atlético de Madrid', logo: 'https://drive.google.com/thumbnail?id=1ta7tkJUgwkYaXXxiRBAXTHU_iHSWHfOw&sz=w200' }
    ]
  },
  {
    name: 'Premier League',
    logo: 'https://drive.google.com/thumbnail?id=1pCySf3QhJlulDzv_8WhJfE5po7Sgz5J6&sz=w200',
    teams: [
      { name: 'Manchester City', logo: 'https://drive.google.com/thumbnail?id=1pCySf3QhJlulDzv_8WhJfE5po7Sgz5J6&sz=w200' },
      { name: 'Arsenal', logo: 'https://drive.google.com/thumbnail?id=1pCySf3QhJlulDzv_8WhJfE5po7Sgz5J6&sz=w200' },
      { name: 'Liverpool', logo: 'https://drive.google.com/thumbnail?id=1pCySf3QhJlulDzv_8WhJfE5po7Sgz5J6&sz=w200' }
    ]
  },
  {
    name: 'Selecciones',
    logo: 'https://drive.google.com/thumbnail?id=1SN6j0_ItHXTVteBqZCfYYZ8TXRNEHS9O&sz=w200',
    teams: [
      { name: 'España', logo: 'https://drive.google.com/thumbnail?id=1SN6j0_ItHXTVteBqZCfYYZ8TXRNEHS9O&sz=w200' },
      { name: 'Alemania', logo: 'https://drive.google.com/thumbnail?id=1SN6j0_ItHXTVteBqZCfYYZ8TXRNEHS9O&sz=w200' },
      { name: 'Argentina', logo: 'https://drive.google.com/thumbnail?id=1SN6j0_ItHXTVteBqZCfYYZ8TXRNEHS9O&sz=w200' }
    ]
  }
];
