import { Jersey, EncargoJersey } from './types';

export const WHATSAPP_NUMBER = '+5355859998';

export const JERSEYS: Jersey[] = [
  // Temporada 25/26
  {
    id: 'rma-home-25-valverde',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1PL8e-1T_GJzW8_fJYkHOVYTktoceqibj',
    style: 'Fan',
    size: 'XL',
    season: '25/26',
    type: 'Local',
    playerName: 'VALVERDE',
    number: '8',
    patch: 'Champions'
  },
  {
    id: 'bar-away-25-kounde',
    name: 'Barcelona - Visitante - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1ycaNuDvea08ARCMCCM0E6U7i4nSII_PY',
    style: 'Fan',
    size: 'XXL',
    season: '25/26',
    type: 'Visitante',
    playerName: 'KOUNDE',
    number: '23',
    patch: 'La Liga'
  },
  {
    id: 'rma-home-25-mbappe',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1u2qHmjqHrqBRMo7r1iGf0lYZcqi2u0TO',
    style: 'Fan',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'MBAPPÉ',
    number: '10',
    patch: 'Champions'
  },
  {
    id: 'bar-home-25-dejong',
    name: 'Barcelona - Local - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1TlV_9qzEPctLo82j69nSobBgHAFZyE2s',
    style: 'Player',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'DE JONG',
    number: '21',
    patch: 'Champions'
  },
  {
    id: 'mia-third-25-messi',
    name: 'Inter de Miami - Tercera - 25/26',
    team: 'Inter de Miami',
    league: 'MLS',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1i_Oxtk6ZPtMMAuOdwt9W-cJ7NFJDz2WC',
    style: 'Player',
    size: 'XL',
    season: '25/26',
    type: 'Tercera',
    playerName: 'MESSI',
    number: '10',
    patch: 'MLS'
  },
  {
    id: 'psg-home-25-dembele',
    name: 'PSG - Local - 25/26',
    team: 'PSG',
    league: 'Ligue 1',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/11MOE3-eNKU3kbnatuY16gJNjXeyplHyB',
    style: 'Player',
    size: 'L',
    season: '25/26',
    type: 'Local',
    playerName: 'DEMBÉLÉ',
    number: '10',
    patch: 'Champions'
  },
  {
    id: 'rma-home-25-bellingham',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1vQR7WbtxXvDz7s9EmlJefSZKDIIDoscD',
    style: 'Player',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'BELLINGHAM',
    number: '5',
    patch: 'Champions'
  },
  {
    id: 'bar-home-25-lamine',
    name: 'Barcelona - Local - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1zgfqFdSpqC7krzHGglYdJ3_Se96VfX3r',
    style: 'Player',
    size: 'XXL',
    season: '25/26',
    type: 'Local',
    playerName: 'LAMINE YAMAL',
    number: '10',
    patch: 'Champions'
  },
  // Temporada 24/25
  {
    id: 'bar-home-24-lewandowski',
    name: 'Barcelona - Local - 24/25',
    team: 'Barcelona',
    league: 'La Liga',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1bp_uMdhYwyU4W1jhM3QPTBp_0RdVJOZ_',
    style: 'Fan',
    size: 'M',
    season: '24/25',
    type: 'Local',
    playerName: 'LEWANDOWSKI',
    number: '9',
    patch: 'Champions'
  },
  {
    id: 'mci-home-24-haaland',
    name: 'Manchester City - Local - 24/25',
    team: 'Manchester City',
    league: 'Premier League',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1LeVhXFpq4zDKFozdUJAcRgaKbGu5hol0',
    style: 'Fan',
    size: 'XL',
    season: '24/25',
    type: 'Local',
    playerName: 'HAALAND',
    number: '9',
    patch: 'Champions'
  },
  // Año 2024
  {
    id: 'esp-home-24-lamine',
    name: 'España - Local - 2024',
    team: 'España',
    league: 'Selecciones',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1z_yJwr8pC_82SFNuOmMar2yeELS59xw9',
    style: 'Fan',
    size: 'XXL',
    season: '2024',
    type: 'Local',
    playerName: 'LAMINE YAMAL',
    number: '19',
    patch: 'Eurocopa'
  },
  // Temporada 22/23
  {
    id: 'psg-home-22-messi',
    name: 'PSG - Local - 22/23',
    team: 'PSG',
    league: 'Ligue 1',
    price: 30,
    image: 'https://lh3.googleusercontent.com/d/1J1MuEWNhT_E2sHJQlLTasCDKZizGq9FZ',
    style: 'Fan',
    size: 'M',
    season: '22/23',
    type: 'Local',
    playerName: 'MESSI',
    number: '30',
    patch: 'Ligue 1'
  },
  // Temporada 14/15
  {
    id: 'rma-retro-14-ronaldo',
    name: 'Real Madrid - Local - 14/15',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1d5VR1wCAhgtQcI6VQ-_6O1YqW-voXcod',
    style: 'Retro',
    size: 'XXL',
    season: '14/15',
    type: 'Local',
    playerName: 'RONALDO',
    number: '7',
    patch: 'Champions'
  },
  {
    id: 'bar-retro-14-suarez',
    name: 'Barcelona - Local - 14/15',
    team: 'Barcelona',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1qavn8778lnjxVqrFtB2ZumQ_N1LLwR4p',
    style: 'Retro',
    size: 'L',
    season: '14/15',
    type: 'Local',
    playerName: 'SUÁREZ',
    number: '9',
    patch: 'Champions'
  },
  // Temporada 13/14
  {
    id: 'rma-retro-13-ramos',
    name: 'Real Madrid - Local - 13/14',
    team: 'Real Madrid',
    league: 'La Liga',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1J8x7pXaTqy1ucwanqlbEBe9rEpUUoRbO',
    style: 'Retro',
    size: 'L',
    season: '13/14',
    type: 'Local',
    playerName: 'SERGIO RAMOS',
    number: '4',
    patch: 'Champions'
  },
  // Temporada 05/06
  {
    id: 'ars-retro-05-henry',
    name: 'Arsenal - Local - 05/06',
    team: 'Arsenal',
    league: 'Premier League',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1-Kjzch1Fjv7IS9LvPclKuzjpoSby41nK',
    style: 'Retro',
    size: 'M',
    season: '05/06',
    type: 'Local',
    playerName: 'HENRY',
    number: '14',
    patch: 'Premier League'
  },
  // Temporada 1990
  {
    id: 'ger-retro-90-matthaus',
    name: 'Alemania - Local - 1990',
    team: 'Alemania',
    league: 'Selecciones',
    price: 35,
    image: 'https://lh3.googleusercontent.com/d/1fZ5zARjTmJOg96y7vKKR4IaC8BUNidqQ',
    style: 'Retro',
    size: 'L',
    season: '1990',
    type: 'Local',
    playerName: 'MATTHÄUS',
    number: '10',
    patch: 'Sin Parche'
  }
];

export const LEAGUES = ['Premier League', 'La Liga', 'Serie A', 'Bundesliga', 'Selecciones'];

export const ENCARGO_JERSEYS: EncargoJersey[] = [
  {
    id: 'fcb-home-25-custom',
    name: 'Barcelona - Local - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Local',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1IaVDX8IyF8d6kAY1Tgbd5ZPmscCfaRiK&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1WXj5Db-O3QS8NFGF0f0ziVlXTf3Uzxgq&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1JhsaUt3V-kcarp--JM6MZrX_A4C7dzLO&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1rPh5PQUvInKbDmx637FaeA3xUSBebSJy&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=17VokuqIUo0IiWrrGGFEUrQZhaoUXH-vh&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1uCG5Ays3HRxaY45B0uIHGj1deAkunQOX&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1kZ7itHKq1E6mDU-zvuSHnzDGiD0wEBMt&sz=w400'
  },
  {
    id: 'fcb-away-25-custom',
    name: 'Barcelona - Visitante - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Visitante',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=141U1mXUKPJgOBJKq4shipF3PPz8JlWnJ&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1yxRcEDVqfCGa0jjLUPWbBqMzO7DM2qjd&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1glKizFCwZ1K4OqZWWs-oXw2am8hFrTDh&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1G6i3w5x9HHr4tbHHsJbAJQ0WxQamjXev&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1TFzZImQB803BH1fu4V_j-IDToRtn3ly-&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1uCG5Ays3HRxaY45B0uIHGj1deAkunQOX&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1kZ7itHKq1E6mDU-zvuSHnzDGiD0wEBMt&sz=w400'
  },
  {
    id: 'fcb-third-25-custom',
    name: 'Barcelona - Tercera - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Tercera',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1MuxdML7QKTrEbcwbi02EEabG8saA77PJ&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=16F49lrFwUDHY6WA_2AoO0O3lhUEGSE8n&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1qX_6rekrALxATHDwqDWnXLEj0NpPBNQ2&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1eAvH9AThCM9nX6zyS9ViDKNZjhgLZvKV&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1js-EPG9kk6mcq5bTuAz_tzhCFQDchp-B&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=16igcA9_OQckLuoAIwD2qxjfP_1gsbG4r&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1IO17l6mDS971b5K4WzRdXFFd5mAqwUwY&sz=w400'
  },
  {
    id: 'fcb-fourth-25-custom',
    name: 'Barcelona - Cuarta - 25/26',
    team: 'Barcelona',
    league: 'La Liga',
    season: '25/26',
    type: 'Cuarta',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1XMPz1YwN6hhuNA6FrkI0MHiy1CwMGpIW&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1G-aw_I9T3k0Z0HRA06RNMattG8UYZ1ph&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1GjRmwtrZ4ZYHHfimL_z9o58MqYRyK6Ir&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1uCG5Ays3HRxaY45B0uIHGj1deAkunQOX&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1kZ7itHKq1E6mDU-zvuSHnzDGiD0wEBMt&sz=w400'
  },
  {
    id: 'rma-home-25-custom',
    name: 'Real Madrid - Local - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Local',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1AH4RKI-MqNVtNjK6rguPg9EeU7LlF2Jq&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1wuGIplPIpXi_1L99PHk05vArGlwZoU2k&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1qE7izWdNW-6DNz9AfVICSomOcwDIIX_F&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1U0ovSfNbZhPowfYv31YM5zonz04zpIx0&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1SxU05Jk6giWUpmpHgOO28AlqPHoc7MkD&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1wnov8L5Fd0DC8-pXUzn0n-ZrkYAz41Ed&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1wnov8L5Fd0DC8-pXUzn0n-ZrkYAz41Ed&sz=w400'
  },
  {
    id: 'rma-away-25-custom',
    name: 'Real Madrid - Visitante - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Visitante',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1CxGWC4Ukwc9mgwqkJVN5apkq0m6mzxZo&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1WmNeCcv4sffZ0aRrQB0Ll7cfHmYC9UEU&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=11JOGBLn88iHoU7TpZhSkTUz0R92abv9k&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1Bo6HC4YyGAI9Q9vaMKTSyQBVmfZs_UDm&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=12w4w495cNSQpZ6U-FsiTvSVL--2naqc7&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1wnov8L5Fd0DC8-pXUzn0n-ZrkYAz41Ed&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1wnov8L5Fd0DC8-pXUzn0n-ZrkYAz41Ed&sz=w400'
  },
  {
    id: 'rma-third-25-custom',
    name: 'Real Madrid - Tercera - 25/26',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '25/26',
    type: 'Tercera',
    price: 30,
    fanImage: 'https://drive.google.com/thumbnail?id=1dboBptHF67paAVK-kAI5mjYOJydu-k_O&sz=w800',
    playerImage: 'https://drive.google.com/thumbnail?id=1kt-l4Meh-0ng-DHLu4mdsQBL87kHosZJ&sz=w800',
    childImage: 'https://drive.google.com/thumbnail?id=1wKMLlecsOHJRWBsyb6FvfP5ZSFfx-UMW&sz=w800',
    fanLongSleeveImage: 'https://drive.google.com/thumbnail?id=1x1rLvp-Ormcd_IfaXFPsXnYFe8sijiFm&sz=w800',
    playerLongSleeveImage: 'https://drive.google.com/thumbnail?id=1zXoAVw3A6htE54m8NKDEhrNVVA8MkXfr&sz=w800',
    fanSizeGuide: 'https://drive.google.com/thumbnail?id=181qCa4uT14HLyJSSTFYPSAoB0SFG792e&sz=w800',
    playerSizeGuide: 'https://drive.google.com/thumbnail?id=1oxhEwRYXV8qJqH33Fugidbsl70MPyOmX&sz=w800',
    childSizeGuide: 'https://drive.google.com/thumbnail?id=1LM40HshR2TghNB0qFuGrHXzvaF1vKXQC&sz=w800',
    ligaNumberingImage: 'https://drive.google.com/thumbnail?id=1wnov8L5Fd0DC8-pXUzn0n-ZrkYAz41Ed&sz=w400',
    championsNumberingImage: 'https://drive.google.com/thumbnail?id=1wnov8L5Fd0DC8-pXUzn0n-ZrkYAz41Ed&sz=w400'
  }
];
